### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by matthias-samwald** [chaochun/nlu-asdiv-dataset#2]
Thanks for the great dataset! It seems like there is no licensing information for the dataset, which makes using the dataset more difficult. Could you please add an (open source) license, or clarify the licensing status? 

See e.g. https://help.figshare.com/article/what-is-the-most-appropriate-licence-for-my-data

Thanks!

**Comment by chaochun** [comment]
We added the licensing information, you can get it from the "Citation" section in the README file. Thanks for your suggestion.

**Comment by matthias-samwald** [comment]
Addressed through https://github.com/chaochun/nlu-asdiv-dataset/commit/883f90a9a65bf00304ba8f37423910fe743abc47
